### ISSUE TITLE
Windows 下添加目录报错

### ISSUE THREAD

**Issue by JeziL** [JeziL/caj2pdf#14]
@mgcwang (in #4 ):
```
D:\caj2pdf-master>python caj2pdf outlines test.caj -o printed.pdf
Traceback (most recent call last):
  File "caj2pdf", line 42, in <module>
    call(["mv", "tmp.pdf", args.output])
  File "D:\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\Python\Python36-32\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

请问，如何排除问题？

--------
刚才又试了试，发现使用caj2pdf的第3条用法为printed.pdf添加目录的时候，虽然显示以上的问题，但是新生成的temp.pdf顺利地把目录添加进去了，而且暂时还没发现temp.pdf文件显示有什么问题，所以是不是就算添加目录成功了？ @JeziL

**Comment by JeziL** [comment]
> 所以是不是就算添加目录成功了？

是的。其实就是在用 tmp.pdf 把 printed.pdf 覆盖掉的时候，偷懒直接调用了 Unix 命令（因为我不用 Windows）……

最新的 commit （[4e23a5b](https://github.com/JeziL/caj2pdf/commit/4e23a5bbe5c69110a62eac4f037e6353c0fa241e)）已经不会有这个报错了，感谢反馈。
