### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by mdfeng** [JeziL/caj2pdf#2]
在调用caj2pdf convert 时，显示转换失败，信息如下：
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
Traceback (most recent call last):
  File "./caj2pdf", line 36, in <module>
    caj.convert(args.output)
  File "/data/opens/caj2pdf/parser.py", line 62, in convert
    self._convert_caj(dest)
  File "/data/opens/caj2pdf/parser.py", line 155, in _convert_caj
    add_outlines(self.get_toc(), "pdf_toc.pdf", dest)
  File "/data/opens/caj2pdf/utils.py", line 156, in add_outlines
    PDF.NameObject("/Dest"): make_dest(pdf_out, t["page"])
  File "/data/opens/caj2pdf/utils.py", line 107, in make_dest
    d.append(pdfw.getPage(pg).indirectRef)
  File "/usr/local/lib/python3.6/site-packages/PyPDF2/pdf.py", line 162, in getPage
    return pages["/Kids"][pageNumber].getObject()
IndexError: list index out of range

**Comment by JeziL** [comment]
@mdfeng 是否方便提供可重现的 caj 文件？

**Comment by mdfeng** [comment]
这里有 
https://github.com/mdfeng/cajfile

**Comment by JeziL** [comment]
@mdfeng 感谢反馈，最新的 commit 应该已经修复。

问题在于添加 Catalog 字典对象时，之前没有多做考虑，是直接将其编号为 `1` 的。而在你提供的两个样本中，这个编号分别与文件中原本存在的对象和根 Pages 对象的编号冲突。

想不到更好的解决方案，目前采取的办法是遍历 1~9999，寻找第一个未被使用的编号作为 Catalog 对象的编号。见 commit [`70bbde4`](https://github.com/JeziL/caj2pdf/commit/70bbde43dc64f501ed2a277ebbcf1c27918c3aaa)。
