### ISSUE TITLE
add_outlines 出错

### ISSUE THREAD

**Issue by gilbert0571** [JeziL/caj2pdf#25]
E:\caj2pdf-master\dist>caj2pdf.exe convert 2.caj -o 2.pdf
PdfReadWarning: Object 325 0 not defined. [pdf.py:1629]
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
  File "cajparser.py", line 65, in convert
  File "cajparser.py", line 220, in _convert_caj
  File "utils.py", line 185, in add_outlines
  File "site-packages\PyPDF2\utils.py", line 159, in __getitem__
  File "site-packages\PyPDF2\utils.py", line 150, in __len__
  File "site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
  File "site-packages\PyPDF2\pdf.py", line 1520, in _flatten
  File "site-packages\PyPDF2\generic.py", line 178, in getObject
  File "site-packages\PyPDF2\pdf.py", line 1631, in getObject
PyPDF2.utils.PdfReadError: Could not find object.
[51116] Failed to execute script caj2pdf

[2.zip](https://github.com/JeziL/caj2pdf/files/2583616/2.zip)

**Comment by JeziL** [comment]
请试一下 [dev](https://github.com/JeziL/caj2pdf/tree/dev) 分支的版本，应该可以成功转换。

**Comment by gilbert0571** [comment]
E:\caj2pdf-master\dist>caj2pdf convert 2.caj -o 2a.pdf
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
  File "cajparser.py", line 63, in convert
  File "cajparser.py", line 142, in _convert_caj
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'pdf.tmp'
[14412] Failed to execute script caj2pdf

注：pdf_toc.pdf 文件生成了，也可以打开，但是一直都是上述错误，文件换了不同的位置也不行。

**Comment by JeziL** [comment]
dev 分支已经修复，谢谢。
