### ISSUE TITLE
请问出现这种情况怎么办？？

### ISSUE THREAD

**Issue by sbkk000** [JeziL/caj2pdf#4]
C:\Users\\***\Desktop\caj2pdf-master>python caj2pdf conver C:\Users\\***\desktop\caj2pdf-master\\***.caj -o .\\***.pdf
Traceback (most recent call last):
  File "caj2pdf", line 5, in <module>
    from parser import CAJParser
ImportError: cannot import name 'CAJParser'

**Comment by JeziL** [comment]
能在该目录下新建一个 Python 文件：
```
import parser
print(parser)
```
然后把它的运行结果贴上来吗

**Comment by JeziL** [comment]
始终没有回复补充一句吧，这个问题我无法复现，但估计是由于模块名冲突，手动把 parser.py 改一下名字（比如 myparser.py），然后对应地修改 caj2pdf 第五行的 import 语句，应该可以解决。 @sbkk000

顺便等待有同学能解答一下难道 Python 的模块搜索策略还有平台差异？

**Comment by sbkk000** [comment]
不好意思这两天回家了
目录下新建的test.py运行结果是
>>> 
============ RESTART: C:\Users\---------\caj2pdf-master\test.py ============
<module 'parser' (built-in)>

改成myparser结果：
>>> 
============ RESTART: C:\Users\---------\caj2pdf-master\test.py ============
Traceback (most recent call last):
  File "C:\Users\cc\Desktop\caj2pdf-master\test.py", line 1, in <module>
    import myparser
ModuleNotFoundError: No module named 'myparser'
>>> 

![image](https://user-images.githubusercontent.com/35765618/35920818-eb74dada-0c53-11e8-8b1b-1656daf58bef.png)
后面这些paser也要改掉么？
![image](https://user-images.githubusercontent.com/35765618/35920949-4e52009c-0c54-11e8-9adf-282c3b9a1448.png)

修改成myparser后结果为

C:\Users\---------\caj2pdf-master>python caj2pdf show .\----------.caj
File: .\----------.caj
Type: CAJ
Page count: **
Outlines count: **

但是运行转换命令就不行了，结果如下

C:\Users\---------\caj2pdf-master>python caj2pdf convert .\------------.caj -o .\-------------.pdf
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
    caj.convert(args.output)
  File "C:\Users\cc\Desktop\caj2pdf-master\myparser.py", line 64, in convert
    self._convert_caj(dest)
  File "C:\Users\cc\Desktop\caj2pdf-master\myparser.py", line 151, in _convert_caj
    catalog_obj_no, root_pages_obj_no), "utf-8")
UnboundLocalError: local variable 'root_pages_obj_no' referenced before assignment

打印好pdf加入目录也不行：
C:\Users\---------\caj2pdf-master>python caj2pdf outlines .\------------.caj -o .\test.pdf
Traceback (most recent call last):
  File "caj2pdf", line 41, in <module>
    add_outlines(toc, args.output, "tmp.pdf")
  File "C:\Users\cc\Desktop\caj2pdf-master\utils.py", line 183, in add_outlines
    pdf_in = PdfFileReader(open(filename, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '.\\test.pdf'

**Comment by JeziL** [comment]
麻烦试一下在 myparser.py 第 129 行后增加一行

```
...
obj_no.append(catalog_obj_no)
root_pages_obj_no = None    # 新增一行
if multi_pages_obj_missed:
...
```

**Comment by sbkk000** [comment]
修改后
![130](https://user-images.githubusercontent.com/35765618/35968183-19b53c46-0cfe-11e8-9901-bac8cd6da9a8.jpg)

运行结果如下
C:\Users\\---------\caj2pdf-master>python caj2pdf convert ------------.caj -o 1.pdf
Traceback (most recent call last):
  File "caj2pdf", line 5, in <module>
    from myparser import CAJParser
  File "C:\Users\\---------\caj2pdf-master\myparser.py", line 130
    root_pages_obj_no = None
___________________________ ^
TabError: inconsistent use of tabs and spaces in indentation

C:\Users\\---------\caj2pdf-master>python caj2pdf outlines ------------.caj -o 1.pdf
Traceback (most recent call last):
  File "caj2pdf", line 5, in <module>
    from myparser import CAJParser
  File "C:\Users\\---------\caj2pdf-master\myparser.py", line 130
    root_pages_obj_no = None
___________________________^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by JeziL** [comment]
用空格缩进

**Comment by sbkk000** [comment]
结果如下
C:\Users\\--------\Desktop\caj2pdf-master>python caj2pdf convert ------------.caj -o 1.pdf
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
    caj.convert(args.output)
  File "C:\Users\\--------\Desktop\caj2pdf-master\myparser.py", line 64, in convert
    self._convert_caj(dest)
  File "C:\Users\\--------\Desktop\caj2pdf-master\myparser.py", line 211, in _convert_caj
    call(["mutool", "clean", "pdf.tmp", "pdf_toc.pdf"])
  File "C:\Users\\--------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\\--------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\\--------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by JeziL** [comment]
[mutool](https://mupdf.com/) 下载了吗，如果下载了你要保证 mutool.exe 可以被命令行调用，或将其路径加入环境变量，或将它直接拷贝到 caj2pdf 目录。
然后后面调用 `rm` 命令删除临时文件的一行：
```
call(["rm", "-f", "pdf.tmp"])
```
在 Windows 下应该也会报错，这个忽略，pdf 文件应该已经生成了。

**Comment by sbkk000** [comment]
是在pip里面安装mutool嚒?

还是下载这个版本的解压到caj2pdf-master同一目录
  | mupdf-1.12.0-windows.zip | 2017-12-13 18:06 | 76M |

**Comment by JeziL** [comment]
mutool 并不是一个 Python 包
下载那个 zip 解压后把 mutool.exe 复制到 caj2pdf 目录

**Comment by sbkk000** [comment]
像这样是吧
![image](https://user-images.githubusercontent.com/35765618/35983673-74f4bce2-0d2d-11e8-953a-00daa3508c16.png)

C:\Users\\---------\caj2pdf-master>python caj2pdf convert 1.caj -o 1.pdf
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
    caj.convert(args.output)
  File "C:\Users\\------------\Desktop\caj2pdf-master\myparser.py", line 64, in convert
    self._convert_caj(dest)
  File "C:\Users\\------------\Desktop\caj2pdf-master\myparser.py", line 211, in _convert_caj
    call(["mutool", "clean", "pdf.tmp", "pdf_toc.pdf"])
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by JeziL** [comment]
mutool.exe not mupdf.exe

**Comment by sbkk000** [comment]
sorry
修改后新的结果是：
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
error: unknown token in dict
error: unknown token in dict
warning: ignoring broken object (1 0 R)
error: unknown token in dict
warning: unknown token in dict
Traceback (most recent call last):
  File "caj2pdf", line 36, in <module>
    caj.convert(args.output)
  File "C:\Users\\------------\Desktop\caj2pdf-master\myparser.py", line 64, in convert
    self._convert_caj(dest)
  File "C:\Users\\------------\Desktop\caj2pdf-master\myparser.py", line 214, in _convert_caj
    add_outlines(self.get_toc(), "pdf_toc.pdf", dest)
  File "C:\Users\\------------\Desktop\caj2pdf-master\utils.py", line 184, in add_outlines
    for p in pdf_in.pages:
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\utils.py", line 159, in __getitem__
    len_self = len(self)
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\utils.py", line 150, in __len__
    return self.lengthFunction()
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
    self._flatten()
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 1505, in _flatten
    catalog = self.trailer["/Root"].getObject()
  File "C:\Users\\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\generic.py", line 516, in __getitem__
    return dict.__getitem__(self, key).getObject()
KeyError: '/Root'

**Comment by JeziL** [comment]
麻烦提供一下 caj 文件我看一下吧，知网链接就行

**Comment by sbkk000** [comment]
http://cdmd.cnki.com.cn/Article/CDMD-10213-1016914904.htm

**Comment by JeziL** [comment]
感谢指出，这是一个 bug，请试一下最新的版本

**Comment by sbkk000** [comment]
感谢~
大部分caj文件已经成功转换。
虽然提示报错：
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
还有部分caj文件出现如下提示：
Unsupported file type.

还有问题是部分扫描版文献无法选取文字，cajviewer里面需要ocr识别。

不支持转换的文献链接部分如下：
1.http://cdmd.cnki.com.cn/Article/CDMD-10703-2005087540.htm
2.http://cdmd.cnki.com.cn/Article/CDMD-10635-1012342629.htm
3.http://cdmd.cnki.com.cn/Article/CDMD-10423-2009160356.htm



建议:以上功能中再加入文件夹文件批量倒入(cajfiles)和处理后文件夹(pdfoutputs)输出。

文件名读取不方便的话，可以先修改文件名（0001-0099.caj）并生成对应列表，
运行批处理bat文件再转换成pdf
（如在caj2pdf-master目录存，放有caj文件的文件夹cajfiles和转换成pdf后的pdfoutputs文件夹，设置一个python caj2pdf convert .\cajfile\0001.caj -o .\pdfoutputs\0001.pdf
*
*
*
python caj2pdf convert .\cajfile\0100.caj -o .\pdfoutputs\0100.pdf
*
*
，或者在cmd中拖入保存好的convert.bat文件），
最后使用rename命令修改caj和pdf回到原文件名。

**Comment by JeziL** [comment]
```
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
```
这是 mutool 修复交叉引用表时的输出，并不是报错。

Unsupported file type 就是字面上的意思，目前仅支持**一部分** caj 文件的转换，请看 README。所以说这个项目目前还很不成熟（可能永远无法成熟 Orz），所以批量转换之类提升易用性的 feature 就暂时往后放了。

**Comment by mgcwang** [comment]
按照上面的方法，我已经能成功实现caj到PDF的转换，非常好用，谢谢开发者！之后，我想向之前用油猴脚本下载好的PDF添加目录（尝试一下caj2pdf的第3条用法），但在cmd中显示如下错误：

```
D:\caj2pdf-master>python caj2pdf outlines test.caj -o printed.pdf
Traceback (most recent call last):
  File "caj2pdf", line 42, in <module>
    call(["mv", "tmp.pdf", args.output])
  File "D:\Python\Python36-32\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\Python\Python36-32\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
```

请问，如何排除问题？
