### ISSUE TITLE
当根 Pages 对象已存在时，寻找其编号的算法存在错误

### ISSUE THREAD

**Issue by JeziL** [JeziL/caj2pdf#6]
By @sbkk000 in issue [#4](https://github.com/JeziL/caj2pdf/issues/4)

```
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
error: unknown token in dict
error: unknown token in dict
warning: ignoring broken object (1 0 R)
error: unknown token in dict
warning: unknown token in dict
Traceback (most recent call last):
File "caj2pdf", line 36, in 
caj.convert(args.output)
File "C:\Users\------------\Desktop\caj2pdf-master\myparser.py", line 64, in convert
self._convert_caj(dest)
File "C:\Users\------------\Desktop\caj2pdf-master\myparser.py", line 214, in _convert_caj
add_outlines(self.get_toc(), "pdf_toc.pdf", dest)
File "C:\Users\------------\Desktop\caj2pdf-master\utils.py", line 184, in add_outlines
for p in pdf_in.pages:
File "C:\Users\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\utils.py", line 159, in getitem
len_self = len(self)
File "C:\Users\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\utils.py", line 150, in len
return self.lengthFunction()
File "C:\Users\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 1155, in getNumPages
self._flatten()
File "C:\Users\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 1505, in _flatten
catalog = self.trailer["/Root"].getObject()
File "C:\Users\------------\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PyPDF2\generic.py", line 516, in getitem
return dict.getitem(self, key).getObject()
KeyError: '/Root'
```

**Comment by JeziL** [comment]
寻找根 Pages 对象时没有逐字节搜索，而是以 6 字节为步长，导致错过对象结束标记。已在 [`6ae3725`](https://github.com/JeziL/caj2pdf/commit/6ae3725f92f7d703008f5beae84ca4ef8549040e) 中修复 。
